# Generated by Django 4.2.23 on 2025-07-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KPI",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("run_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("value", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "kpi",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("csv_file", models.CharField(max_length=255)),
                ("output_format", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=20)),
                ("rows_processed", models.IntegerField()),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "run",
                "managed": False,
            },
        ),
    ]
