version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "your-github-username"  # Replace with your actual GitHub username
    assignees:
      - "your-github-username"  # Replace with your actual GitHub username
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-github-username"  # Replace with your actual GitHub username
    assignees:
      - "your-github-username"  # Replace with your actual GitHub username
    commit-message:
      prefix: "ci"
      include: "scope"

  # Enable version updates for Docker base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-github-username"  # Replace with your actual GitHub username
    assignees:
      - "your-github-username"  # Replace with your actual GitHub username
    commit-message:
      prefix: "docker"
      include: "scope" 